### ISSUE TITLE
Crazy heights when screen is resized

### ISSUE THREAD

**Issue by samg0ddard** [KurtPreston/isortope#14]
Hi love the plugin and it's working great however my table is having some issues on certain screen sizes, the table is given a height that's 100's of pixels taller than it should be, any idea what might be causing this issue? Cheers! Sam

**Comment by KurtPreston** [comment]
Can you send an example?

Does the table initialize to a bogus height, or does it just look off when the window is resized?

**Comment by KurtPreston** [comment]
Closing due to lack of response.  Please re-open if this is still an issue, and you can provide an example.
