### ISSUE TITLE
Sorting groups

### ISSUE THREAD

**Issue by aHumanBeing** [KurtPreston/isortope#16]
I have a table dynamically populated with records falling into 1 of 3 different groups.  The first group contains record of a particular priority sorted by time, the second group contains records of a particular activity sorted by time, and the third group includes all other records sorted by time. The time can either be a duration of an event or a counter showing how long an even is in session.  

Would it be possible to use this plugin to auto sort my table by time with respect to the 3 groups?

Thank you

**Comment by KurtPreston** [comment]
I've updated the code to add rudimentary support for multiple groups.  Make sure to update to the most recent version (1.2.2).

Then, try putting each group in a separate tbody element.  Something like:

```html
<table>
  <thead>
    ...
  </thead>
  <tbody>
    <tr>...</tr>
    <tr>...</tr>
  </tbody>
  <tbody>
    <tr>...</tr>
    <tr>...</tr>
  </tbody>
</table>

**Comment by aHumanBeing** [comment]
Thank you. Unfortunately, project requirements have changed and I no longer need this. I truly appreciate the effort!
