### ISSUE TITLE
Fixed height of table set by isortope always different from actual height

### ISSUE THREAD

**Issue by troycono** [KurtPreston/isortope#18]
Hey there,

Even in the demo on your website, the table height extends past the bottom of the containing section element. On the site I'm currently trying to implement this with, the height of the table varies from being far too short for the containing div to far too tall for it. I'm betting that padding and margin on the tr's or td's of the tbody element is to blame, but since I need those in order to make my table display pretty, how can I account for that in isortope so that the outputting table height is set correctly based on the padding and margin settings of each row?

**Comment by troycono** [comment]
For whomever may find this experiencing the same issue, and for you, Kurt, the developer whose live demo itself displays the very issue I'm talking about, this is the fix you are looking for. The following jquery (wrapped in a document.ready function) code will make the height of your isortope table match the height of its tbody element, which is always the correct height based on your padding/margin settings in your stylesheet for the table rows, no matter how many of them there are. Without this, your isortope tables will always be either way too short or way too tall for their container. I wish I knew why, but at least I know how to work around it from now on:

` 
/* Capture the inline, css set height of the tbody element (not the calculated height) */
var tableHeight = jQuery('table.isortope tbody').get(0).style.height;
/* Reset isortope's default inline css height setting on the table */
$('table.isortope').css('height', '');
$('table.isortope').css('height', null);
/* Make the height of the table match that of the css defined, inline height of its tbody */
$('table.isortope').css('height', tableHeight);`

**Comment by KurtPreston** [comment]
@troycono Nice sleuthing!

I poked around for a bit, and It seems like the underlying issue is that the height of ```tr``` elements somehow gets changed during Isortope initialization, making them taller than in the original table.

I've pushed out an update that should fix the issue for you.  Please re-open the issue if you still are noticing anything strange.
